### ISSUE TITLE
MySQL - ?useSSL=false Not Working

### ISSUE THREAD

**Issue by Webman97** [BattlePlugins/BattleTracker-3.0#15]
I've tried many combinations of adding "?useSSL=false", nothing has worked thus far. It is very unclear how to add this functionality to the config, and I did not locate any documentation that advises how to do this. How is this plugin handling JDBC connections?

**Comment by Redned235** [comment]
> I've tried many combinations of adding "?useSSL=false", nothing has worked thus far. It is very unclear how to add this functionality to the config, and I did not locate any documentation that advises how to do this. How is this plugin handling JDBC connections?

Connections are handled in our BattleCore dependency in the [SQLSerializer](https://github.com/BattlePlugins/BattleCore/blob/7ec5bcd121b4d264ee7c5440751faf1db86a4540/src/main/java/mc/alk/v1r7/serializers/SQLSerializer.java) class. What is it exactly you are trying to achieve?

**Comment by Webman97** [comment]
I'm trying to get rid of the following message:

`WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.`

**Comment by Redned235** [comment]
> I'm trying to get rid of the following message:
> 
> `WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.`

Ah I see. This is something we'd need need to add support for. Thanks!

**Comment by Webman97** [comment]
> Ah I see. This is something we'd need need to add support for. Thanks!

Good to know, thank you!

**Comment by Zach443** [comment]
I’m already working with database code this weekend. I will look into this

**Comment by Zach443** [comment]
@Webman97 Where are you adding `?useSSLfalse` ? In the config, under the database url field?

**Comment by Webman97** [comment]
@Zach443 As I said, I've tried many combinations of adding `?useSSL=false`. This includes placing `?useSSL=false` next to the database name, database url, port number, & username (obviously not all at once).

I expect the jdbc query to end up like this: `jdbc:mysql://hostname:3306/dbname?useSSL=false`, so in my latest attempt I placed `?useSSL=false` next to the database name.

**Comment by clovisd** [comment]
Closing, Expecting SQL implementation to be different with BT Rewrite.
